#spring.application.name=trippass
#server.port=9091


server:
  port: 9091
  forward-headers-strategy: framework

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: [openid, profile, email]
            #redirect-uri: "http://localhost:9091/login/oauth2/code/google"
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:9091/login/oauth2/code/google}

        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://openidconnect.googleapis.com/v1/userinfo
            user-name-attribute: sub